//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ГлазаЗеркалоДуши
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Agent()
        {
            this.AgentPriorityHistory = new HashSet<AgentPriorityHistory>();
            this.ProductSale = new HashSet<ProductSale>();
            this.Shop = new HashSet<Shop>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public int AgentTypeID { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Logo { get; set; }
        public string Address { get; set; }
        public int Priority { get; set; }
        public string DirectorName { get; set; }
        public string INN { get; set; }
        public string KPP { get; set; }

        public string BackColor { get
            {
                if (Discount >= 25) return "LightGreen";
                else return "White";
            } }
        public string LogoPath { get
            {
                if (Logo != null)
                    return "image" + Logo;
                else
                    return null;
            }
        }
    // общее кол-во единиц продукции за последний год - продажи

        public int Sales
        {
            get
            {
                int s = 0;
                DateTime today = DateTime.Today;
                DateTime year = today.AddYears(-1);
                foreach (ProductSale ps in ProductSale) {
                    if (ps.SaleDate >= year)
                    {
                        s += ps.ProductCount;
                    }      
                }
                return s;
            }
        }

    // по общей цене продаж скидка
        public int Discount
        {
            get
            {
                if (ID % 10 == 0)
                    return 25;
                else
                {
                    float price = 0;
                    foreach (ProductSale ps in ProductSale)
                    {
                        price += (float)(ps.TotalPrice);
                    }
                    if (price < 10000)
                        return 0;
                    else if (price < 50000)
                        return 5;
                    else if (price < 150000)
                        return 10;
                    else if (price < 500000)
                        return 20;
                    else
                        return 25;
                }
            }
        }
        public virtual AgentType AgentType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AgentPriorityHistory> AgentPriorityHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductSale> ProductSale { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shop> Shop { get; set; }
    }
}
